viewer_last_update = """
    SELECT
        TO_DATE(DT_VIGENCIA,'DD/MM/YY') DT_VIGENCIA,
        TO_CHAR(DT_VIGENCIA, 'DD/MM/YYYY') VIGENCIA,
        CD_TAB_FAT TABELA,
        NM_USUARIO USUARIO
    FROM
        DBAMV.VAL_PRO
    WHERE
        DT_VIGENCIA >= TO_DATE('01/01/25', 'DD/MM/YY')
    GROUP BY TO_DATE(DT_VIGENCIA, 'DD/MM/YY'), CD_TAB_FAT, NM_USUARIO, TO_CHAR(DT_VIGENCIA, 'DD/MM/YYYY') 
    ORDER BY 1
"""